[package]
name = "acctblty_int"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
acctblty = { path = ".." }
sha2 = { version = "0.10" }
hmac = "0.12"
rand = { version = "0.8" }
curve25519-dalek = { version = "4.1", features = [ "serde", "digest" ]}
